version: "3.9"
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: test_nest_db

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: test_nest_db
      PORT: 3002

  token-service:
    build:
      context: ./token-service
      dockerfile: Dockerfile
    container_name: token-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: test_nest_db
      PORT: 3001

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_nest_db

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
